### ISSUE TITLE
After "npm start" -> Error

### ISSUE THREAD

**Issue by ghost** [ALiangLiang/cloud9-launcher#1]
```
npm start

> cloud9-launcher@0.0.1 start /var/www/cloud9-launcher
> node app.js

/var/www/cloud9-launcher/app.js:68
  .post(async function(req, res) {
        ^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by ALiangLiang** [comment]
@alessnapolitano  Do you use nodejs version upper than 6?
