### ISSUE TITLE
Dockerize 

### ISSUE THREAD

**Issue by knkrth** [ALiangLiang/cloud9-launcher#3]
Hi, Is the any plans on Dockerize the container so that they can run in isolation. Possible update of https://github.com/farukcank/cloud9wsman/tree/develop

**Comment by ALiangLiang** [comment]
Do you mean let me update this project?

karthik <notifications@github.com> 於 2019年9月5日 週四 16:51 寫道：

**Comment by knkrth** [comment]
Yes, Everything works fine while running it on Node V4 but when  I updated the all npm package to the latest version & run it on Node v10 I got the following error while trying to login using `username:admin password:admin`,
```
Server started listening on 0.0.0.0:8080
ERROR: TypeError: Cannot read property '{"salt":"U\u0005c+«5þ£!]\u0010êë¡.ëáÈ\u0018\u0019KÊÒ¹4õ¾","password":"admin"}' of undefined
ERROR: TypeError: Cannot read property '{"salt":"U\u0005c+«5þ£!]\u0010êë¡.ëáÈ\u0018\u0019KÊÒ¹4õ¾","password":"admin"}' of undefined
    at pbkdf2 (/home/workspace/cloud9/auth.js:29:15)
    at verifyPW (/home/workspace/cloud9/auth.js:56:12)
    at /home/workspace/cloud9/db.js:237:16
    at _fulfilled (/home/workspace/cloud9/node_modules/q/q.js:854:54)
    at /home/workspace/cloud9/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/workspace/cloud9/node_modules/q/q.js:816:13)
    at /home/workspace/cloud9/node_modules/q/q.js:624:44
    at runSingle (/home/workspace/cloud9/node_modules/q/q.js:137:13)
    at flush (/home/workspace/cloud9/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

`package.json`
```
"devDependencies": {
    "config": "~3.2.2",
    "http-proxy": "~1.17.0",
    "node-cache": "~4.2.1",
    "q": "~1.5.1",
    "redis": "~2.8.0",
    "serve-static": "^1.14.1"
  },
```

**Comment by knkrth** [comment]
Using Mysql as a database & signup feature would be nice to implement init.

**Comment by knkrth** [comment]
@ALiangLiang Are you planning to update the code to support the latest node js with some additional features?

**Comment by ALiangLiang** [comment]
um... Sorry I have no plan to update the project. I'm busy recently.

**Comment by knkrth** [comment]
Ok
